name: Workflow-CI-Mayang_Gumelar

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_data_liver.csv"
  TARGET_VAR: "Target"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo "CSV file path: $CSV_URL"
          echo "Target variable: $TARGET_VAR"
          python --version
          pip --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install mlflow pandas scikit-learn joblib numpy

      - name: Set MLflow Tracking URI
        run: |
          export MLFLOW_TRACKING_URI="http://127.0.0.1:5000"
          echo "MLflow Tracking URI set to $MLFLOW_TRACKING_URI"

      - name: Run mlflow project
        run: |
          echo "Running MLflow project..."
          python MLproject/modelling.py

      - name: Install Python dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Upload to Google Drive
        env:
          GDRIVE_FOLDER: "MLflow_Results"
        run: |
          echo "Simulasi upload hasil training ke Google Drive folder: $GDRIVE_FOLDER"

      - name: Complete job
        run: echo "Workflow selesai dijalankan!"
